# Generated by Django 5.2.16 on 2026-09-12 18:52

import client_calendar.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_workspace_and_more'),
        ('projects', '0011_project_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCalendarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_link', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('POST', 'Feed post'), ('CAROUSEL', 'Carousel'), ('REEL', 'Reel / video'), ('STORY', 'Story'), ('AD_LAUNCH', 'Ad campaign launch'), ('AD_CHANGE', 'Ad optimisation'), ('AD_REVIEW', 'Campaign review'), ('CREATIVE', 'Creative for approval'), ('REPORT', 'Performance report'), ('MEETING', 'Meeting / call'), ('WEBSITE', 'Website update'), ('OTHER', 'Other')], default='POST', max_length=12)),
                ('platform', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('X', 'X (Twitter)'), ('GOOGLE_ADS', 'Google Ads'), ('META_ADS', 'Meta Ads'), ('WEBSITE', 'Website'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], max_length=12)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('APPROVAL', 'Awaiting client approval'), ('DONE', 'Done'), ('POSTPONED', 'Postponed')], default='PLANNED', max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, help_text="Leave blank if it isn't tied to a time of day.", null=True)),
                ('title', models.CharField(help_text='Written for the client — they will read this.', max_length=160)),
                ('details', models.TextField(blank=True, help_text="Caption, what's changing, or what the review covers.")),
                ('link', models.URLField(blank=True, help_text='The live post, ad preview, report or Drive folder.', max_length=500)),
                ('preview', models.ImageField(blank=True, upload_to=client_calendar.models._preview_path)),
                ('show_to_client', models.BooleanField(default=True, help_text="Untick to keep a draft off the client's calendar.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'client activities',
                'ordering': ['date', 'time', 'id'],
                'indexes': [models.Index(fields=['project', 'date'], name='client_cale_project_4bcffe_idx'), models.Index(fields=['date', 'show_to_client'], name='client_cale_date_1b1388_idx')],
            },
        ),
    ]
