# Generated by Django 5.2.16 on 2026-09-12 20:11

import client_calendar.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_calendar', '0001_initial'),
        ('clients', '0002_client_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('APPROVAL', 'Awaiting client approval'), ('APPROVED', 'Approved by client'), ('DONE', 'Done'), ('POSTPONED', 'Postponed')], default='PLANNED', max_length=12),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for the client'), ('APPROVED', 'Approved'), ('CHANGES', 'Changes requested'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('message', models.TextField(blank=True, help_text='A note to the client: what to look at, what you need.')),
                ('content', models.TextField(blank=True, help_text='The copy to approve — caption, blog text, ad text.')),
                ('respond_by', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status_before', models.CharField(blank=True, max_length=12)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='client_calendar.clientactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_count', models.PositiveSmallIntegerField(default=0)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='client_calendar.approvalrequest')),
            ],
            options={
                'ordering': ['reviewer__name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=200, upload_to=client_calendar.models._approval_path)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='client_calendar.approvalrequest')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_epoch', models.PositiveIntegerField(default=1)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='clients.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.contact')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_calendar.clientreviewer'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='reviewers',
            field=models.ManyToManyField(related_name='approval_requests', through='client_calendar.ApprovalRecipient', to='client_calendar.clientreviewer'),
        ),
        migrations.AddField(
            model_name='approvalrecipient',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='client_calendar.clientreviewer'),
        ),
        migrations.CreateModel(
            name='ApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SENT', 'Sent for approval'), ('REMINDED', 'Reminder sent'), ('OPENED', 'Opened'), ('APPROVED', 'Approved'), ('CHANGES', 'Requested changes'), ('WITHDRAWN', 'Withdrawn')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client_calendar.approvalrequest')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_calendar.clientreviewer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientreviewer',
            constraint=models.UniqueConstraint(fields=('client', 'email'), name='client_reviewer_unique_email'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'activity'], name='client_cale_status_697373_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrecipient',
            constraint=models.UniqueConstraint(fields=('request', 'reviewer'), name='approval_recipient_unique'),
        ),
    ]
