# Generated by Django 5.2.16 on 2026-09-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_calendar', '0002_client_approvals'),
        ('clients', '0002_client_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreviewer',
            name='last_update_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientreviewer',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientreviewer',
            name='update_frequency',
            field=models.CharField(choices=[('SOON', 'As things change'), ('DAILY', 'Daily summary'), ('WEEKLY', 'Weekly summary'), ('OFF', 'Off')], default='OFF', max_length=8),
        ),
        migrations.AddField(
            model_name='clientreviewer',
            name='updates_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('ADDED', 'Newly planned'), ('MOVED', 'Rescheduled'), ('DONE', 'Published or done'), ('POSTPONED', 'Postponed'), ('RESUMED', 'Back on the plan'), ('REMOVED', 'Taken off the calendar')], max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('activity_kind', models.CharField(blank=True, max_length=12)),
                ('platform', models.CharField(blank=True, max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('old_date', models.DateField(blank=True, null=True)),
                ('old_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_calendar.clientactivity')),
                ('announced_to', models.ManyToManyField(blank=True, related_name='+', to='client_calendar.clientreviewer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_updates', to='clients.client')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='client_cale_client__349c65_idx')],
            },
        ),
    ]
