# Generated by Django 5.2.16 on 2026-07-26 11:44

import django.db.models.deletion
import resource_planner.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_hours', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Hours available on a normal working day.', max_digits=4)),
                ('working_days', models.CharField(default='12345', help_text='ISO weekday digits, 1 (Mon) to 7 (Sun). Default 12345.', max_length=7, validators=[resource_planner.models._validate_working_days])),
                ('weekly_hours_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to derive from daily hours × working days.', max_digits=5, null=True)),
                ('monthly_hours_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to derive from the weekly figure.', max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capacity profile',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick leave'), ('HOLIDAY', 'Public holiday'), ('COMP_OFF', 'Comp off'), ('UNPAID', 'Unpaid leave'), ('OTHER', 'Other')], default='VACATION', max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False, help_text='Halves the capacity of every day in the range.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for a company-wide holiday.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='resource_pl_start_d_1927b0_idx'), models.Index(fields=['user', 'start_date'], name='resource_pl_user_id_4563f9_idx')],
            },
        ),
    ]
