# Generated by Django 5.2.16 on 2026-08-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agencysettings_default_annual_leave_days'),
        ('resource_planner', '0002_seed_resource_planning_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='decision_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='kind',
            field=models.CharField(choices=[('VACATION', 'Earned / vacation'), ('CASUAL', 'Casual leave'), ('SICK', 'Sick leave'), ('HOLIDAY', 'Public holiday'), ('COMP_OFF', 'Comp off'), ('UNPAID', 'Unpaid leave'), ('OTHER', 'Other')], default='VACATION', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reason'),
        ),
        migrations.AddIndex(
            model_name='leaverecord',
            index=models.Index(fields=['status', 'start_date'], name='resource_pl_status_567c2f_idx'),
        ),
    ]
