# Generated by Django 5.2.16 on 2026-07-19 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('is_auto', models.BooleanField(default=False, help_text="Auto-managed by code; can't be toggled by hand")),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
