# Generated by Django 5.2.16 on 2026-07-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_actual_hours_task_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogentry',
            name='approval_status',
            field=models.CharField(choices=[('NONE', 'Draft'), ('SUBMITTED', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='worklog_screenshots/'),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklogentry',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank for project-level work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='worklogentry',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-filled from start/end when blank.', max_digits=5, null=True),
        ),
    ]
