# Generated by Django 5.2.16 on 2026-07-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_worklogentry_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
