# Generated by Django 5.2.16 on 2026-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_backfill_milestone_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_url',
            field=models.URLField(blank=True, help_text='Google Drive (or similar) link, used for files over the size limit', max_length=500),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='external_url',
            field=models.URLField(blank=True, help_text='Google Drive (or similar) link, used for files over the size limit', max_length=500),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='label',
            field=models.CharField(blank=True, help_text='Shown instead of the URL for linked files', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, upload_to='project_assets/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, upload_to='task_attachments/'),
        ),
    ]
