# Generated by Django 5.2.16 on 2026-08-09 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_asset_external_url_taskattachment_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='People who can see this project. Managers see every project regardless of this list.', related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
