# Generated by Django 5.2.16 on 2026-08-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_workspace_and_more'),
        ('core', '0004_workspace_activitylog_workspace_and_more'),
        ('projects', '0010_backfill_project_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'is_archived'], name='projects_pr_workspa_66e648_idx'),
        ),
    ]
