# Generated by Django 5.2.16 on 2026-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='external_url',
            field=models.URLField(blank=True, help_text='Google Drive (or similar) link, used for files over the size limit', max_length=500),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, upload_to='employee_docs/'),
        ),
    ]
