# Generated by Django 5.2.16 on 2026-08-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agencysettings_default_annual_leave_days'),
        ('employees', '0004_employeeprofile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='annual_leave_days',
            field=models.PositiveIntegerField(blank=True, help_text='Paid leave days per year. Leave blank to use the agency default from Agency settings.', null=True),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month this covers.')),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_days_taken', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leave_days_allowed', models.PositiveIntegerField(default=0)),
                ('excess_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Bonus (positive) or other deduction (negative).', max_digits=12)),
                ('adjustment_note', models.CharField(blank=True, max_length=200)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SKIPPED', 'Not payable')], default='PENDING', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('BANK', 'Bank transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=10)),
                ('reference', models.CharField(blank=True, help_text='UTR, cheque number, transaction id — whatever ties this to the bank record.', max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employeeprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='core.workspace')),
            ],
            options={
                'ordering': ['-month', 'employee__user__first_name'],
                'indexes': [models.Index(fields=['month', 'status'], name='employees_s_month_cabe74_idx'), models.Index(fields=['workspace', '-month'], name='employees_s_workspa_2751f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='unique_salary_month')],
            },
        ),
    ]
