# Generated by Django 5.2.16 on 2026-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysettings',
            name='state',
            field=models.CharField(blank=True, help_text='Place of supply, e.g. Telangana. Used to split GST into CGST/SGST or IGST.', max_length=100),
        ),
    ]
