# Generated by Django 5.2.16 on 2026-08-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agencysettings_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('is_home', models.BooleanField(default=False, help_text='The agency that owns this install. Exactly one workspace.')),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_home', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['workspace', '-created_at'], name='core_activi_workspa_7233f2_idx'),
        ),
    ]
