# Generated by Django 5.2.16 on 2026-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_home_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysettings',
            name='default_annual_leave_days',
            field=models.PositiveIntegerField(default=18, help_text='Paid leave days per year, before excess is deducted from salary. Can be raised for an individual on their HR record.'),
        ),
    ]
