# Generated by Django 5.2.16 on 2026-07-19 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_template_back_image'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('MILESTONE', 'Milestone'), ('FINAL', 'Final settlement'), ('OTHER', 'Other')], default='MILESTONE', max_length=12)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], default='UPI', max_length=16)),
                ('reference', models.CharField(blank=True, help_text='Txn id / cheque no / UPI ref', max_length=120)),
                ('received_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional: the invoice this payment settles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
    ]
