# Generated by Django 5.2.16 on 2026-07-26 13:22

import calendar_hub.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_ratelimit_loginotp'),
        ('clients', '0001_initial'),
        ('projects', '0008_asset_external_url_taskattachment_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('MEETING', 'Meeting'), ('EVENT', 'Event')], default='MEETING', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('meeting_url', models.URLField(blank=True, help_text='Video call link — Meet, Zoom, Teams.', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Inclusive last day. Leave blank for a single-day event.', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Leave blank for an all-day event.', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=8)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Every N days/weeks/months/years.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('weekdays', models.CharField(blank=True, help_text="Weekly only: ISO digits, 1 (Mon) to 7 (Sun). Blank repeats on the start date's own weekday.", max_length=7, validators=[calendar_hub.models._validate_weekdays])),
                ('repeat_until', models.DateField(blank=True, help_text='Last day the series can land on.', null=True)),
                ('repeat_count', models.PositiveSmallIntegerField(blank=True, help_text='Stop after this many occurrences.', null=True, validators=[django.core.validators.MaxValueValidator(750)])),
                ('visibility', models.CharField(choices=[('AGENCY', 'Everyone'), ('PRIVATE', 'Organiser and attendees only')], default='AGENCY', max_length=8)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, default=60, help_text='Minutes before the start to notify attendees.', null=True)),
                ('external_provider', models.CharField(blank=True, help_text='Set by an external calendar integration; blank for local events.', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=250)),
                ('attendees', models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, help_text='Filled from the project when one is chosen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='accounts.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.project')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_date', models.DateField()),
                ('moved_to', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar_hub.calendarevent')),
            ],
            options={
                'ordering': ['original_date'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=120)),
                ('event_date', models.DateField()),
                ('kind', models.CharField(choices=[('REMINDER', 'Event reminder'), ('DEADLINE', 'Upcoming deadline')], default='REMINDER', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_date', 'end_date'], name='calendar_hu_start_d_5a9293_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['frequency', 'start_date'], name='calendar_hu_frequen_02a73d_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_provider', 'external_id'), name='unique_external_calendar_event'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['event', 'original_date'], name='calendar_hu_event_i_80fd9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.UniqueConstraint(fields=('event', 'original_date'), name='unique_event_occurrence'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['event_date'], name='calendar_hu_event_d_99a14d_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('source_key', 'event_date', 'user', 'kind'), name='unique_reminder_delivery'),
        ),
    ]
