# Generated by Django 5.2.16 on 2026-08-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_workspace'),
        ('calendar_hub', '0001_initial'),
        ('clients', '0002_client_workspace_and_more'),
        ('core', '0004_workspace_activitylog_workspace_and_more'),
        ('projects', '0011_project_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['workspace', 'start_date'], name='calendar_hu_workspa_571ebc_idx'),
        ),
    ]
