# Generated by Django 5.2.16 on 2026-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lock_core_writes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Business Owner'), ('SALES', 'Sales'), ('PM', 'Project Manager'), ('DEV', 'Developer'), ('ACCT', 'Accounts')], default='', max_length=10),
        ),
    ]
