# Generated by Django 5.2.16 on 2026-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ratelimit_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_all',
            field=models.BooleanField(default=False),
        ),
    ]
