# Generated by Django 5.2.16 on 2026-08-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grant_view_all_and_restrict_reporting'),
        ('core', '0004_workspace_activitylog_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text="Which partition this person works in. Leave unset for your own agency's staff.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.workspace'),
        ),
    ]
