# Generated by Django 5.2.16 on 2026-07-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='template',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='css',
        ),
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.AddField(
            model_name='template',
            name='content_background',
            field=models.ImageField(blank=True, help_text='Background repeated on content pages (A4)', null=True, upload_to='templates/content/'),
        ),
        migrations.AddField(
            model_name='template',
            name='content_height',
            field=models.FloatField(default=76.0),
        ),
        migrations.AddField(
            model_name='template',
            name='content_width',
            field=models.FloatField(default=84.0),
        ),
        migrations.AddField(
            model_name='template',
            name='content_x',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='template',
            name='content_y',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='template',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Full-page cover design (page 1, A4)', null=True, upload_to='templates/covers/'),
        ),
    ]
