# Generated by Django 5.2.16 on 2026-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Constant last page (back / thank-you, A4)', null=True, upload_to='templates/backs/'),
        ),
    ]
