# Generated by Django 5.2.16 on 2026-07-24 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_template_back_image'),
        ('projects', '0006_milestone_completed_on_recurringtask_anchor_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='unique_document_number'),
        ),
    ]
