# Generated by Django 5.2.16 on 2026-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_unique_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_due_date',
            field=models.DateField(blank=True, help_text='Shown on the calendar as a review deadline.', null=True),
        ),
    ]
