# Generated by Django 5.2.16 on 2026-08-19 11:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_review_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_priced',
            field=models.BooleanField(default=False, help_text='Itemised pricing: line items, GST and totals computed server-side.'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit', models.CharField(blank=True, help_text='Optional unit, e.g. "hrs", "pages", "mo"', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST % charged on this line', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
